version: "3"

services: 
 log: 
   build:
      context: .
   ports:
      - "8000:8000"
   volumes: 
      - ./log:/log
   command: >
       # sh -c "virtualenv env"

      # > sh -c "source /env/bin/activate"

         sh -c "python manage.py runserver 0.0.0.0:8000"
