# Generated by Django 2.2.5 on 2019-09-10 11:22

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20190909_1600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='tutorial_published',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 10, 11, 22, 42, 778526, tzinfo=utc), verbose_name='date published'),
        ),
    ]
