# Generated by Django 2.1.5 on 2019-09-14 18:15

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20190910_1122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='tutorial_published',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 14, 18, 15, 15, 469102, tzinfo=utc), verbose_name='date published'),
        ),
    ]
